### ISSUE TITLE
Invalid spacer length of `XLMOD:02258`

### ISSUE THREAD

**Issue by althonos** [HUPO-PSI/xlmod-CV#1]
The `XLMOD:02558` has an invalid spacer length annotation property:
```obo
[Term]
id: XLMOD:02258
property_value: spacerLength: "5.0-20.0" xsd:float
```
This is used to indicate a range, however this can cause later issues because of the datatype being marked as `xsd:float`, such as generating invalid OWL files where the float literals are indeed not floats. To fix this I'd suggest adding two new annotation properties `minSpacerLength` and `maxSpacerLength` and use them to indicate a range.

In addition, it would be nice to declare the annotation properties properly in the OBO file, and have proper identifiers for them (`spacerLength` instead of `spacerLength:`).

I can submit a PR if you want :+1:

**Comment by edeutsch** [comment]
Thank you, a PR would be much appreciated!
